/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaGradle;

public class Library {
	private String myString;
	
	public Library(String myString) {
		this.myString = myString;
	}
	
	public void updateString() {
		myString.toLowerCase();
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
    
    
}
